"""create document versions table

Revision ID: 2bf528e359d8
Revises: ca75d1d0311a
Create Date: 2026-09-16 13:08:20.134403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf528e359d8'
down_revision: Union[str, Sequence[str], None] = 'ca75d1d0311a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('supersedes_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_versions')
    # ### end Alembic commands ###
