"""create claim correspondences table

Revision ID: ce34a3b89993
Revises: e4050f42c737
Create Date: 2026-09-17 11:39:20.150299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce34a3b89993'
down_revision: Union[str, Sequence[str], None] = 'e4050f42c737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_correspondences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_a_id', sa.UUID(), nullable=False),
    sa.Column('claim_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_a_id', 'claim_b_id', name='uq_claim_correspondence_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_correspondences')
    # ### end Alembic commands ###
