"""create policy change tables

Revision ID: d1fdddab439c
Revises: ce34a3b89993
Create Date: 2026-09-17 12:15:57.623812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fdddab439c'
down_revision: Union[str, Sequence[str], None] = 'ce34a3b89993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('reason_claim_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reason_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_change_claims',
    sa.Column('policy_change_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['policy_change_id'], ['policy_changes.id'], ),
    sa.PrimaryKeyConstraint('policy_change_id', 'claim_id')
    )
    op.create_table('policy_change_correspondences',
    sa.Column('policy_change_id', sa.UUID(), nullable=False),
    sa.Column('correspondence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['correspondence_id'], ['claim_correspondences.id'], ),
    sa.ForeignKeyConstraint(['policy_change_id'], ['policy_changes.id'], ),
    sa.PrimaryKeyConstraint('policy_change_id', 'correspondence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_change_correspondences')
    op.drop_table('policy_change_claims')
    op.drop_table('policy_changes')
    # ### end Alembic commands ###
