import { CheckCircle2, Database, Globe2, SlidersHorizontal, Sparkles, Wifi } from "lucide-react";
import { PageHeader } from "../components/PageHeader";

export function Settings() {
  return <div className="page-enter mx-auto max-w-[920px] px-5 py-7 md:px-8 md:py-10 lg:px-10"><PageHeader eyebrow="Workspace controls" title="Settings" description="Configuration controls will be connected to the backend as the workspace moves from demo data to live regulatory monitoring." /><div className="space-y-4"><div className="rounded-2xl border border-[#dce6e8] bg-white p-6"><div className="flex items-start gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3f4] text-[#4c7985]"><SlidersHorizontal size={17} /></div><div><h2 className="text-[14px] font-semibold text-[#2d5464]">API connection</h2><p className="mt-1 text-[12px] leading-6 text-[#819198]">Set <code className="rounded bg-[#f1f5f5] px-1.5 py-0.5 text-[11px] text-[#4c707b]">VITE_API_BASE_URL</code> to connect this frontend to the existing FastAPI backend.</p></div></div><div className="mt-5 rounded-xl border border-[#d8e8e5] bg-[#f1f8f5] px-4 py-3 text-[11px] text-[#5f817d]"><CheckCircle2 size={14} className="mr-1.5 inline-block" /> Demo mode active · no live API requests are made.</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#dce6e8] bg-white p-5"><Globe2 size={18} className="text-[#6b9299]" /><h2 className="mt-4 text-[13px] font-semibold text-[#345b69]">Language display</h2><p className="mt-1.5 text-[11px] leading-5 text-[#85969c]">English UI with original evidence language preserved. Amharic rendering can be added without duplicating claims.</p></div><div className="rounded-2xl border border-[#dce6e8] bg-white p-5"><Sparkles size={18} className="text-[#719c9a]" /><h2 className="mt-4 text-[13px] font-semibold text-[#345b69]">AI transparency</h2><p className="mt-1.5 text-[11px] leading-5 text-[#85969c]">Extraction and interpretation remain clearly separated from evidence-backed conclusions.</p></div></div></div></div>;
}

export function SystemStatus() {
  return <div className="page-enter mx-auto max-w-[920px] px-5 py-7 md:px-8 md:py-10 lg:px-10"><PageHeader eyebrow="Operational health" title="System status" description="A simple view of the services that support the intelligence workflow." /><div className="rounded-2xl border border-[#cce3dc] bg-[#eff8f4] p-6"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8eee6] text-[#3f8277]"><Wifi size={19} /></div><div><h2 className="font-display text-xl font-semibold text-[#275e5c]">All systems operational</h2><p className="mt-1 text-[12px] text-[#6d8986]">Demo environment healthy · Last checked just now</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[#d5e9e2] bg-white/70 p-4"><Database size={16} className="text-[#5a9489]" /><div className="mt-3 text-[11px] font-semibold text-[#4e7775]">API boundary</div><div className="mt-1 text-[10px] text-[#86a09c]">Ready for FastAPI</div></div><div className="rounded-xl border border-[#d5e9e2] bg-white/70 p-4"><CheckCircle2 size={16} className="text-[#5a9489]" /><div className="mt-3 text-[11px] font-semibold text-[#4e7775]">Evidence library</div><div className="mt-1 text-[10px] text-[#86a09c]">Demo records indexed</div></div><div className="rounded-xl border border-[#d5e9e2] bg-white/70 p-4"><Globe2 size={16} className="text-[#5a9489]" /><div className="mt-3 text-[11px] font-semibold text-[#4e7775]">Source monitor</div><div className="mt-1 text-[10px] text-[#86a09c]">4 sources checked</div></div></div></div></div>;
}
